<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Browser launch Successfully]]>
    </line>
    <line>
      <![CDATA[ScreenShot taken for TC102]]>
    </line>
  </reporter-output>
  <suite started-at="2022-04-05T12:51:40 IST" name="Default suite" finished-at="2022-04-05T12:52:09 IST" duration-ms="28762">
    <groups>
    </groups>
    <test started-at="2022-04-05T12:51:40 IST" name="Default test" finished-at="2022-04-05T12:52:09 IST" duration-ms="28762">
      <class name="kiteTestClasse.UserIdValidateUsingPropertyFile">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:kiteTestClasse.UserIdValidateUsingPropertyFile@4d154ccd]" started-at="2022-04-05T12:51:40 IST" name="launchBrowser" finished-at="2022-04-05T12:52:04 IST" duration-ms="24136" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Browser launch Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="login()[pri:0, instance:kiteTestClasse.UserIdValidateUsingPropertyFile@4d154ccd]" started-at="2022-04-05T12:52:04 IST" name="login" finished-at="2022-04-05T12:52:05 IST" duration-ms="683" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="validateUserId()[pri:0, instance:kiteTestClasse.UserIdValidateUsingPropertyFile@4d154ccd]" started-at="2022-04-05T12:52:05 IST" name="validateUserId" finished-at="2022-04-05T12:52:07 IST" duration-ms="2047" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at kiteTestClasse.UserIdValidateUsingPropertyFile.validateUserId(UserIdValidateUsingPropertyFile.java:56)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateUserId -->
        <test-method is-config="true" signature="logout(org.testng.ITestResult)[pri:0, instance:kiteTestClasse.UserIdValidateUsingPropertyFile@4d154ccd]" started-at="2022-04-05T12:52:07 IST" name="logout" finished-at="2022-04-05T12:52:08 IST" duration-ms="996" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validateUserId status=FAILURE method=UserIdValidateUsingPropertyFile.validateUserId()[pri:0, instance:kiteTestClasse.UserIdValidateUsingPropertyFile@4d154ccd] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ScreenShot taken for TC102]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:kiteTestClasse.UserIdValidateUsingPropertyFile@4d154ccd]" started-at="2022-04-05T12:52:08 IST" name="closeBrowser" finished-at="2022-04-05T12:52:09 IST" duration-ms="834" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- kiteTestClasse.UserIdValidateUsingPropertyFile -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
